services:
  spread-bot:
    build: .
    container_name: spread-bot
    command: python bot.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always

  parser:
    build: .
    container_name: futures-parser
    command: python tg_parser.py
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./sessions:/app/sessions
    restart: always
